[package]
name = "lily-cst"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
peekmore = "1.0.0"
unicode_categories = "0.1.1"
